name: VIP Customer CICD workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Frontend Image
        run: |
          docker build ./frontend -t vip-customer-web:v1
          docker tag vip-customer-web:v1 kennedyuche/vip-customer-web:v1
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push kennedyuche/vip-customer-web:v1