name: VIP Customer CICD workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  build-push-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build Frontend Image
        run: |
          docker build ./frontend -t vip-customer-web:v1
          docker tag vip-customer-web:v1 kennedyuche/vip-customer-web:v1
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vip-customer-web:v1
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          script: |
            az aks get-credentials --resource-group ${{ secrets.AZ_RESOURCE_GROUP }} --name ${{ secrets.AZ_CLUSTER }}

      - name: Setup kubectl and Deploy to k8s
        uses: azure/setup-kubectl@v3
        with:
          script: |
            cd kubernetes
            kubectl apply -f -
            kubectl rollout restart deployment vip-customer-web -n vip-customer-app