name: VIP Customer CICD workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-push-images:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: vip-customer-web:v1

      # - name: Build and push backend
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./backend
      #     push: true
      #     tags: vip-customer-api:v1

      # - name: Docker-Compose run
      #   uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "./docker-compose.yml"
      #     down-flags: "--volumes"
      #     services: |
      #       frontend
      #       backend

      - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd hng-project-25 && git pull
          docker-compose up